// <auto-generated />
using System;
using EnergyTrade.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace EnergyTrade.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EnergyTradeDbContext))]
    partial class EnergyTradeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EnergyTrade.Domain.Entities.EnergyOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE")
                        .HasColumnName("CREATED_AT");

                    b.Property<int>("Currency")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CURRENCY");

                    b.Property<DateTimeOffset>("DeliveryEnd")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE")
                        .HasColumnName("DELIVERY_END");

                    b.Property<DateTimeOffset>("DeliveryStart")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE")
                        .HasColumnName("DELIVERY_START");

                    b.Property<int>("EnergyType")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ENERGY_TYPE");

                    b.Property<decimal>("PricePerMWh")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("PRICE_PER_MWH");

                    b.Property<decimal>("QuantityMWh")
                        .HasPrecision(18, 3)
                        .HasColumnType("DECIMAL(18,3)")
                        .HasColumnName("QUANTITY_MWH");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("SELLER_ID");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STATUS");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.ToTable("ENERGY_OFFERS", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
