<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>d9aa2715-a231-4916-8f96-817dbc7cb8df</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EnergyTrade.Application\EnergyTrade.Application.csproj" />
    <ProjectReference Include="..\EnergyTrade.Infrastructure\EnergyTrade.Infrastructure.csproj" />
  </ItemGroup>

</Project>
